local describe = require("syzygy").describe

describe("expect", function ()
    require("test.expect.toBe")
    require("test.expect.toBeCloseTo")
    require("test.expect.toBeTruthy")
    require("test.expect.toBeFalsy")
    require("test.expect.toBeGreaterThan")
    require("test.expect.toBeGreaterThanOrEqual")
    require("test.expect.toBeLessThan")
    require("test.expect.toBeLessThanOrEqual")
    require("test.expect.toBeNil")
    require("test.expect.toContain")
    require("test.expect.toEqual")
    require("test.expect.toHaveLength")
    require("test.expect.toMatch")
    require("test.expect.toMatchObject")
end)
