name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

env:
  LUA_BUILD_VERSION: "5.4"

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ github.token }}
          version: latest
          args: --check .

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua: ["5.3", "5.4"]

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-and-build
        with:
          luaVersion: ${{ env.LUA_BUILD_VERSION }}

      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{ matrix.lua }}

      - run: lua -v

      - name: Run tests
        run: make test

      - name: Run tests with artifact
        run: make test-dist
